name: Windows (MinGW)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      JAVA_HOME: ${{ env.JAVA_HOME_21_X64 }}
    steps:
      - uses: actions/checkout@v4

      - name: "Setup cmake"
        run: cmake --version

      - name: "Setup gil"
        run: |
          pip3 install gil
          gil update

      - name: "Build"
        env:
          INCLUDE: C:\mingw64\x86_64-w64-mingw32\include
          LIB: C:\mingw64\x86_64-w64-mingw32\lib
        run: |
          cd build
          ./mingw.bat
